return {
  -- 'catppuccin/nvim',
  -- name = 'catppuccin',
  -- priority = 1000, -- Make sure it's loaded early
  -- config = function()
  --   require('catppuccin').setup {
  --     flavour = 'mocha', -- latte, frappe, macchiato, mocha
  --     background = {
  --       light = 'latte',
  --       dark = 'mocha',
  --     },
  --     transparent_background = true,
  --     show_end_of_buffer = false,
  --     term_colors = true,
  --     dim_inactive = {
  --       enabled = false,
  --       shade = 'dark',
  --       percentage = 0.15,
  --     },
  --     no_italic = false,
  --     no_bold = false,
  --     no_underline = false,
  --     styles = {
  --       comments = { 'italic' },
  --       conditionals = { 'italic' },
  --       loops = {},
  --       functions = {},
  --       keywords = { 'bold' },
  --       strings = {},
  --       variables = {},
  --       numbers = {},
  --       booleans = {},
  --       properties = {},
  --       types = {},
  --       operators = {},
  --     },
  --     color_overrides = {},
  --     custom_highlights = {},
  --     integrations = {
  --       cmp = true,
  --       gitsigns = true,
  --       nvimtree = true,
  --       telescope = true,
  --       treesitter = true,
  --       treesitter_context = true,
  --       which_key = true,
  --       -- For more plugins integrations see: https://github.com/catppuccin/nvim#integrations
  --     },
  --   }

  --   -- Apply the colorscheme
  --   vim.cmd.colorscheme 'catppuccin'

  --   -- Manual highlight overrides for transparency
  --   -- Cursor line must be transparent for theme transparency to work
  --   vim.api.nvim_set_hl(0, 'CursorLine', {})

  --   -- Visual selection - transparent background with visible text
  --   vim.api.nvim_set_hl(0, 'Visual', { fg = '#cdd6f4', bold = true, italic = true })
  -- end,
}
